# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{rails-settings}
  s.version = "0.1.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Philip Schalm", "Felix McCoey"]
  s.date = %q{2010-09-19}
  s.email = %q{pnomolos@gmail.com}
  s.extra_rdoc_files = [
    "LICENSE",
     "README",
     "TODO"
  ]
  s.files = [
    "Gemfile",
     "LICENSE",
     "README",
     "Rakefile",
     "TODO",
     "VERSION",
     "lib/rails-settings.rb",
     "lib/rails-settings/adapters/common.rb",
     "lib/rails-settings/adapters/datamapper/init.rb",
     "lib/rails-settings/adapters/datamapper/map.rb",
     "lib/rails-settings/adapters/datamapper/model.rb",
     "lib/rails-settings/initializer.rb",
     "lib/rails-settings/railtie.rb",
     "lib/rails-settings/scoped.rb",
     "rails-settings.gemspec"
  ]
  s.homepage = %q{http://github.com/pnomolos/rails-settings}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{A nice little settings plugin for Rails}

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<dm-timestamps>, [">= 0.9.4"])
      s.add_runtime_dependency(%q<dm-validations>, [">= 0.9.4"])
    else
      s.add_dependency(%q<dm-timestamps>, [">= 0.9.4"])
      s.add_dependency(%q<dm-validations>, [">= 0.9.4"])
    end
  else
    s.add_dependency(%q<dm-timestamps>, [">= 0.9.4"])
    s.add_dependency(%q<dm-validations>, [">= 0.9.4"])
  end
end

